directories:
  output: release
  buildResources: resources
productName: Мой пирожочек
appId: org.develar.my_cake
files:
  - filter:
      - app/dist/
      - app/app.html
      - app/main.prod.js
      - app/main.prod.js.map
      - package.json
dmg:
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
win:
  target:
    - nsis
    - msi
nsis:
  allowElevation: false
  allowToChangeInstallationDirectory: true
  oneClick: false
  perMachine: true
linux:
  target:
    - deb
    - rpm
    - snap
    - AppImage
  category: Development
electronVersion: 3.0.10
